django_impl/demo/urls.py
from django.conf.urls import url

from demo.forms import AuthForm
from . import views
from django.contrib.auth import views as auth_views


app_name = 'demo'
urlpatterns = [
  url(r'^login/$', auth_views.login, kwargs={"authentication_form":AuthForm}, name='login'),
  url(r'^logout/$', auth_views.logout, {'next_page': '/demo/login'}, name='logout'),
  url(r'^signup/$', views.signup, name='signup'),
  url(r'^add/$', views.IndexView.as_view(), name='add'),
  url(r'^edit/(?P<mapid>[0-9]+)/$', views.IndexView.as_view(),name='edit'),
  url(r'^delete/(?P<mapid>[0-9]+)/$', views.IndexView.as_view(),name='delete'),
  url(r'^$', views.IndexView.as_view(), name='index'),
]

django_impl/mapdemo/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'',        include('demo.urls')),
    url(r'^demo/',  include('demo.urls')),
    url(r'^admin/', admin.site.urls),
]

django_impl/demo/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class Maps(models.Model):
  """
  Map data for all users, includes upper-left corner and lower-right corner of maps.
  """
  uid = models.ForeignKey(User,on_delete=models.CASCADE)  # a user may have > 1 map
  upper_long = models.DecimalField(max_digits=9, decimal_places=6)  # suggestion from: http://stackoverflow.com/questions/30706799/which-model-field-to-use-in-django-to-store-longitude-and-latitude-values
  upper_lat  = models.DecimalField(max_digits=9, decimal_places=6)
  lower_long = models.DecimalField(max_digits=9, decimal_places=6)
  lower_lat  = models.DecimalField(max_digits=9, decimal_places=6)
  map_name   = models.CharField(max_length=200)  # user may give nickname to the map, default will be "Map Created On <UTC ts>"
  pub_date = models.DateTimeField('date made')

  def __str__(self):
    return "user: {}; upperlat: {}; upperlong: {}; lowerlat: {}; lowerlong: {}".format(self.uid.username, self.upper_lat, self.upper_long,
                                                                                       self.lower_lat, self.lower_long, self.map_name)

class Marks(models.Model):
  mapid = models.ForeignKey(Maps, on_delete=models.CASCADE)  # a map may have > 1 mark
  mark_long =  models.DecimalField(max_digits=9, decimal_places=6)
  mark_lat  =  models.DecimalField(max_digits=9, decimal_places=6)
  name = models.CharField(max_length=200)
  description = models.TextField()
  residents = models.IntegerField(default=-1)

  def __str__(self):
    return "map: {}; lat: {}; long: {};".format(self.mapid, self.mark_lat, self.mark_long)

django_impl/demo/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm


class UserForm(forms.Form):
  username = forms.CharField(label="Username")
  password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'autocomplete':'new-password'}))


# special form so that we can jam in the
# autocomplete attribute for the password input field
class AuthForm(AuthenticationForm):
  password = forms.CharField(
    label=("Password"),
    strip=False,
    widget=forms.PasswordInput(attrs={"autocomplete":"new-password"}),
  )

django_impl/demo/views.py
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.csrf import csrf_protect

from .models import Maps, Marks
from django.contrib.auth.decorators import login_required
from forms import UserForm

from django.views.decorators.debug import sensitive_post_parameters

@sensitive_post_parameters("password")
@csrf_protect
def signup(request):
  if request.method == "POST":
    form = UserForm(request.POST)  # form = UserForm(request.POST)
    if form.is_valid():
      try:
        new_user = User.objects.create_user(**form.cleaned_data)
        # login(new_user, redirect_authenticated_user=True, redirect_field_name="/")
        # redirect, or however you want to get to the main view
        return HttpResponseRedirect('/demo/login')
      except Exception as e:
        print e
        form=UserForm()
  else:
    form = UserForm()
  return render(request, 'demo/signup.html', {'form': form})


class AddMap(LoginRequiredMixin, generic.DetailView):
  template_name = ''

# todo: could setup caching to prevent recalculating the model everytime...
class IndexView(LoginRequiredMixin, generic.ListView):
  template_name = 'demo/index.html'
  context_object_name = 'model'

  def get_queryset(self):
    model = {
      'maps': Maps.objects.filter(uid_id=self.request.user.id).order_by('-pub_date'),  # user's maps
      'current_map': None,                                                   # most recent map
      'current_marks': None,                                                 # marks for most recent map
    }
    model["current_map"] = model["maps"][0] if len(model["maps"]) > 0 else None  # grab the most recent map as the one to be viewed
    model["current_marks"] = Marks.objects.filter(mapid_id=model["current_map"].id) if model["current_map"] else None
    return model



# class DetailView(LoginRequiredMixin, generic.DetailView):
#   model = Question
#   template_name = 'demo/details.html'
#
# class ResultsView(LoginRequiredMixin, generic.DetailView):
#   model = Question
#   template_name = 'demo/results.html'
#
# @login_required
# def vote(request, question_id):
#   question = get_object_or_404(Question, pk=question_id)
#   try:
#     selected_choice = question.choice_set.get(pk=request.POST['choice'])
#   except (KeyError, Choice.DoesNotExist):
#     # Redisplay the question voting form.
#     return render(request, 'demo/details.html', {
#       'question': question,
#       'error_message': "You didn't select a choice.",
#     })
#   else:
#     selected_choice.votes += 1
#     selected_choice.save()
#     # Always return an HttpResponseRedirect after successfully dealing
#     # with POST data. This prevents data from being posted twice if a
#     # user hits the Back button.
#     return HttpResponseRedirect(reverse('demo:results', args=(question.id,)))

django_impl/demo/templates/demo/base.html
{% load static %}
<html>
<head>
    <title>Map Demo</title>
    <!--font awesome-->
    <link rel="stylesheet" href="{% static 'demo/font-awesome/css/font-awesome.min.css' %}">

    <!--jquery-->
    <script src="{% static 'demo/jquery/jquery-3.1.1.min.js' %}"></script>

    <!--materialize stuff-->
    <link rel="stylesheet" href="{% static 'demo/materialize/css/materialize.min.css' %}">
    <script src="{% static 'demo/materialize/js/materialize.min.js' %}"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!--map box stuff-->
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.28.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.28.0/mapbox-gl.css' rel='stylesheet' />

    <style>
        body {
            display: flex;
            min-height: 100vh;
            flex-direction: column;
        }

        main {
            flex: 1 0 auto;
        }
    </style>
</head>
<body>
<header>
    <div class="navbar-fixed">
        <nav>
            <div class="nav-wrapper grey darken-3">
                <a style="left:20px; position:absolute;"> <i class="fa fa-globe"></i> {{ user.username }}'s maps </a>
                <a href="/#" class="brand-logo center">MapDemo</a>
                <ul id="nav-mobile" class="right">
                    <li><a style="font-size:20px;" href="/logout"><i class="material-icons left">ic_exit_to_app</i>Logout</a></li>
                </ul>
            </div>
        </nav>
    </div>
</header>

<main>
    <div>
        {% block content %}
        {% endblock %}
    </div>
    <script>
        mapboxgl.accessToken = 'pk.eyJ1Ijoic3BucnBhIiwiYSI6ImNpd2FtYXFmYjA0M20zMm1zb3RiNnJieGMifQ.bIttLrrEpj64CRokEwvSNQ';
        var map = new mapboxgl.Map({
            container: 'map',
            style: 'mapbox://styles/mapbox/streets-v9',
            center: [-74.50, 40],
            zoom: 9
        });
        var bounds = map.getBounds();
    </script>
</main>

<footer class="page-footer light-blue darken-3" style="padding-top:0; z-index:1;">
    <div class="footer-copyright light-blue darken-3">
        <div class="container" style="left:20px;">
            2016 Map Demo By Spencer Aiello
            <a class="grey-text text-lighten-4 right" style="text-decoration:underline;" href="#!">More Links</a>
        </div>
    </div>
</footer>
</body>
</html>

django_impl/demo/templates/demo/index.html
{% extends 'demo/base.html' %}

{% block content %}
<div>
    <ul id="nav-mobile" class="collection with-header side-nav fixed" style="transform: translateX(0px);z-index:0; top:65px;">
        <li class="collection-header center"><h4>My Maps</h4></li>
        <li class="collection-item">Map 1</li>
        <li class="collection-item">Map 2</li>
        <li class="collection-item">Map 3</li>
        <li class="collection-item">Map 4</li>
    </ul>
</div>
{% if model and model.current_map %}
<p>
    {{ model.maps }}
    {{ model.current_map }}
    {{ model.current_marks }}
</p>
{% else %}
<p>no maps...</p>
{% endif %}
<div style="width:80%;min-width:100px;height:60px;">
    <div class="input-field col s6" style="left:350px; top=-17px; width:20%;">
        <i class="material-icons prefix" style="line-height:1.5;">mode_edit</i>
        <textarea style="padding:0;" id="mapname" class="materialize-textarea"></textarea>
        <label for="mapname">Map Name</label>
    </div>
    <div style="top:-50px; position:relative; left:800px; display:inline-block;">
        <p>N.E. (Long, Lat): (<input id="ne_lng" style="width:100px;height:20px;">,<input id="ne_lat" style="width:100px;height:20px;">)</p>
        <p style="position:absolute; left:350px;top:0px; width:450px;">S.W. (Long, Lat): (<input id="sw_lng" style="width:92px;height:20px;">,<input id="sw_lat" style="width:92px;height:20px;">)</p>
        <a id="locator" style="left:-50px;top:-75px;" class="btn-floating black tooltipped" data-position="top" data-delay="50" data-tooltip="Fit to Location"><i class="material-icons">gps_fixed</i></a>
    </div>
</div>
<div id='map' style="width: 60%; height: 80%;left: 350px;"></div>
<div class="fixed-action-btn horizontal" style="bottom:60px;">
    <a class="btn-floating btn-large red">
        <i class="large material-icons">mode_edit</i>
    </a>
    <ul>
        {% if model.current_map %}
        <li><a href="{% url 'demo:delete' model.current_map.id %}" class="btn-floating red tooltipped" data-position="top" data-delay="50" data-tooltip="Delete Map"><i class="material-icons">delete_forever</i></a></li>
        <li><a href="{% url 'demo:edit'   model.current_map.id  %}" class="btn-floating green tooltipped" data-position="top" data-delay="50" data-tooltip="Edit Map"><i class="material-icons">build</i></a></li>
        {% endif %}
        <li><a href="{% url 'demo:add' %}"  class="btn-floating blue tooltipped" data-position="top" data-delay="50" data-tooltip="Add Map"><i class="material-icons">add</i></a></li>
    </ul>
</div>
<script>
        var setbounds = function(bounds) {
            document.getElementById("ne_lng").value = bounds._ne.lng.toFixed(6);
            document.getElementById("ne_lat").value = bounds._ne.lat.toFixed(6);
            document.getElementById("sw_lng").value = bounds._sw.lng.toFixed(6);
            document.getElementById("sw_lat").value = bounds._sw.lat.toFixed(6);
            <!--console.log("NE: [" + bounds._ne.lat + ", " + bounds._ne.lng + "]; SW: [" + bounds._sw.lat + ", " + bounds._sw.lng + "];");-->
        };
        $(document).ready(function() {
            var i;
            console.log(map);
            console.log(bounds);
            setbounds(bounds);
            var isMouseDown = false;
            document.getElementById("locator").addEventListener("click", function() {
                ne_lng = document.getElementById("ne_lng").value;
                ne_lat = document.getElementById("ne_lat").value;
                sw_lng = document.getElementById("sw_lng").value;
                sw_lat = document.getElementById("sw_lat").value;
                try {
                    map.fitBounds([[ne_lng, ne_lat], [sw_lng, sw_lat]]);
                } catch(err) {
                    Materialize.toast('Illegal Input! Resetting map.', 4000, 'red')
                    map= new mapboxgl.Map({
                        container: 'map',
                        style: 'mapbox://styles/mapbox/streets-v9',
                        center: [-74.50, 40],
                        zoom: 9
                    });
                    setbounds(map.getBounds());
                }
            });
            document.onmousedown = function() { isMouseDown = true  };
            document.onmouseup   = function() { isMouseDown = false; clearInterval(i); };
            document.onmousemove = function(e) {
                if(isMouseDown) {
                    if( i==null ) { /* only set interval once when moving and mousedown....*/
                        if( e.target.className == "mapboxgl-canvas" )
                            i=setInterval(function() { bounds = map.getBounds(); setbounds(bounds); }, 10);
                    }
                } else {
                    clearInterval(i);
                    i=null;
                }
            };
        });
        </script>
{% endblock %}

django_impl/demo/templates/demo/signup.html
{% load static %}
<html>
<head>
    <title>Map Demo</title>
    <link rel="stylesheet" href="{% static 'demo/materialize/css/materialize.min.css' %}">
    <link rel="stylesheet" href="{% static 'demo/font-awesome/css/font-awesome.min.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="{% static 'demo/jquery/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'demo/materialize/js/materialize.min.js' %}"></script>
    <style>
        body {
            display: flex;
            min-height: 100vh;
            flex-direction: column;
        }

        main {
            flex: 1 0 auto;
        }
    </style>
</head>
<body>

<main>
    <div style="position:relative; left:37%; top:75px; min-width:1500px;">
        <div class="row">
            <div class="col s12 m3">
                <div class="card z-depth-5">
                    <div class="card-content blue darken-1 white-text">
                        <span class="card-title">Sign Up</span>
                    </div>
                    <div class="card-action">
                        <form method="post" action="">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="row">
                                    <div class="col s12">
                                        <div class="input-field inline">
                                            {{ field }}
                                            <label for="{{ field.name }}" data-error="wrong" data-success="right">{{ field.label }}</label>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="row" style="white-space:nowrap;">
                                <button class="btn waves-effect waves-light blue darken-1 right" type="submit" name="action">Submit
                                    <i class="material-icons right">send</i>
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

<footer class="page-footer light-blue darken-3" style="padding-top:0;">
    <div class="footer-copyright light-blue darken-3">
        <div class="container" style="left:20px;">
            2016 Map Demo By Spencer Aiello
            <a class="grey-text text-lighten-4 right" style="text-decoration:underline;" href="#!">More Links</a>
        </div>
    </div>
</footer>
</body>
</html>